"""Sensor definitions for Solar Cube."""
from __future__ import annotations

SENSOR_DEFINITIONS = [
    {
        "key": "grid_active_power",
        "name": "Grid Active Power",
        "measurement": "data",
        "field": "_sum/GridActivePower",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "key": "pv_active_power",
        "name": "PV Active Power",
        "measurement": "data",
        "field": "_sum/ProductionActivePower",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "key": "ess_active_power",
        "name": "ESS Active Power",
        "measurement": "data",
        "field": "_sum/EssActivePower",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "key": "consumption_active_power",
        "name": "Consumption Active Power",
        "measurement": "data",
        "field": "_sum/ConsumptionActivePower",
        "unit": "W",
        "device_class": "power",
        "state_class": "measurement",
    },
    {
        "key": "grid_voltage_l1",
        "name": "Grid L1 Voltage",
        "measurement": "data",
        "field": "meter0/VoltageL1",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "division": 1000,
    },
    {
        "key": "grid_voltage_l2",
        "name": "Grid L2 Voltage",
        "measurement": "data",
        "field": "meter0/VoltageL2",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "division": 1000,
    },
    {
        "key": "grid_voltage_l3",
        "name": "Grid L3 Voltage",
        "measurement": "data",
        "field": "meter0/VoltageL3",
        "unit": "V",
        "device_class": "voltage",
        "state_class": "measurement",
        "division": 1000,
    },
    {
        "key": "grid_buy_active_energy",
        "name": "Grid Buy Active Energy",
        "measurement": "data",
        "field": "_sum/GridBuyActiveEnergy",
        "unit": "Wh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "grid_sell_active_energy",
        "name": "Grid Sell Active Energy",
        "measurement": "data",
        "field": "_sum/GridSellActiveEnergy",
        "unit": "Wh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "pv_active_energy",
        "name": "PV Active Energy",
        "measurement": "data",
        "field": "_sum/ProductionActiveEnergy",
        "unit": "Wh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "consumption_active_energy",
        "name": "Consumption Active Energy",
        "measurement": "data",
        "field": "_sum/ConsumptionActiveEnergy",
        "unit": "Wh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "ess_charge_energy",
        "name": "ESS Charge Energy",
        "measurement": "data",
        "field": "_sum/EssActiveChargeEnergy",
        "unit": "Wh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "ess_discharge_energy",
        "name": "ESS Discharge Energy",
        "measurement": "data",
        "field": "_sum/EssActiveDischargeEnergy",
        "unit": "Wh",
        "device_class": "energy",
        "state_class": "total_increasing",
    },
    {
        "key": "ess_soc",
        "name": "ESS SoC",
        "measurement": "data",
        "field": "_sum/EssSoc",
        "unit": "%",
        "device_class": "battery",
        "state_class": "measurement",
    },
    {
        "key": "buy_energy_price",
        "name": "Buy Energy Price",
        "measurement": "cs",
        "field": "cs/prices/buy_total_price_per_kwh",
        "unit": "per kWh",
        "bucket": "agents",
        "range_start": "-60m",
    },
    {
        "key": "sell_energy_price",
        "name": "Sell Energy Price",
        "measurement": "cs",
        "field": "cs/prices/sell_price_per_kwh",
        "unit": "per kWh",
        "bucket": "agents",
        "range_start": "-60m",
    },
    {
        "key": "controller_id",
        "name": "Controller ID",
        "measurement": "cs",
        "field": "cs/schedule/controller",
        "bucket": "agents",
        "range_start": "-60m",
    },
    {
        "key": "target_soc",
        "name": "Target SoC",
        "measurement": "cs",
        "field": "cs/schedule/target_soc",
        "unit": "%",
        "bucket": "agents",
        "range_start": "-60m",
    },
    {
        "key": "optimised_energy_total_savings",
        "name": "Optimised Energy Total Savings",
        "measurement": "cs",
        "field": "cs/prices/total_savings",
        "unit": "currency",
        "device_class": "monetary",
        "bucket": "agents",
        "range_start": "-1h",
    },
    # Scalar optimal action fields (also available inside the Optimal Actions payload).
    {
        "key": "optimal_actions_bc",
        "name": "Optimal Actions BC",
        "measurement": "cs",
        "field": "cs/opt_actions/bc",
        "bucket": "agents",
        "range_start": "-60m",
    },
    {
        "key": "optimal_actions_bg",
        "name": "Optimal Actions BG",
        "measurement": "cs",
        "field": "cs/opt_actions/bg",
        "bucket": "agents",
        "range_start": "-60m",
    },
    {
        "key": "optimal_actions_gb",
        "name": "Optimal Actions GB",
        "measurement": "cs",
        "field": "cs/opt_actions/gb",
        "bucket": "agents",
        "range_start": "-60m",
    },
    {
        "key": "optimal_actions_gc",
        "name": "Optimal Actions GC",
        "measurement": "cs",
        "field": "cs/opt_actions/gc",
        "bucket": "agents",
        "range_start": "-60m",
    },
    {
        "key": "optimal_actions_pb",
        "name": "Optimal Actions PB",
        "measurement": "cs",
        "field": "cs/opt_actions/pb",
        "bucket": "agents",
        "range_start": "-60m",
    },
    {
        "key": "optimal_actions_pc",
        "name": "Optimal Actions PC",
        "measurement": "cs",
        "field": "cs/opt_actions/pc",
        "bucket": "agents",
        "range_start": "-60m",
    },
    {
        "key": "optimal_actions_pg",
        "name": "Optimal Actions PG",
        "measurement": "cs",
        "field": "cs/opt_actions/pg",
        "bucket": "agents",
        "range_start": "-60m",
    },
]
